-- Generated by okasurya 20160101 0059
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IDHAZE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IDHAZE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IDHAZE` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `IDHAZE` ;

-- -----------------------------------------------------
-- Table `IDHAZE`.`Hotspot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IDHAZE`.`Hotspot` (
  `HotspotID` INT NOT NULL AUTO_INCREMENT,
  `Longitude` VARCHAR(45) NOT NULL,
  `Latitude` VARCHAR(45) NOT NULL,
  `Confidence` DECIMAL(2) NOT NULL,
  `Region` INT NULL,
  `Provinsi` VARCHAR(225) NULL,
  `Kabupaten` VARCHAR(225) NULL,
  `Kecamatan` VARCHAR(225) NULL,
  `EntryDate` DATETIME NOT NULL,
  `LastUpdatedTime` DATETIME NULL,
  PRIMARY KEY (`HotspotID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IDHAZE`.`KabupatenKota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IDHAZE`.`KabupatenKota` (
  `KabupatenKotaID` VARCHAR(255) NOT NULL,
  `Nama` VARCHAR(255) NOT NULL,
  `ProvinsiID` VARCHAR(255) NULL,
  PRIMARY KEY (`KabupatenKotaID`),
  UNIQUE INDEX `KABKOTA_PK` (`KabupatenKotaID` ASC),
  INDEX `MEMILIKI_PROVINSI_FK` (`Nama` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `IDHAZE`.`Kecamatan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IDHAZE`.`Kecamatan` (
  `KecamatanID` VARCHAR(255) NOT NULL,
  `KabupatenKotaID` VARCHAR(255) NOT NULL,
  `Nama` VARCHAR(255) NULL,
  PRIMARY KEY (`KecamatanID`),
  UNIQUE INDEX `KECAMATAN_PK` (`KecamatanID` ASC),
  INDEX `MEMILIKI_KABKOTA_FK` (`KabupatenKotaID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `IDHAZE`.`Provinsi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IDHAZE`.`Provinsi` (
  `ProvinsiID` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(255) NULL DEFAULT NULL,
  `KodePeta` VARCHAR(255) NULL,
  PRIMARY KEY (`ProvinsiID`),
  UNIQUE INDEX `PROVINSI_PK` (`ProvinsiID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `IDHAZE`.`SchemaChanges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IDHAZE`.`SchemaChanges` (
  `SchemaChangeID` INT NOT NULL AUTO_INCREMENT,
  `MajorReleaseNumber` VARCHAR(2) NOT NULL,
  `MinorReleaseNumber` VARCHAR(2) NOT NULL,
  `PointReleaseNumber` VARCHAR(2) NOT NULL,
  `ScriptName` VARCHAR(50) NOT NULL,
  `DateApplied` DATETIME NOT NULL,
  PRIMARY KEY (`SchemaChangeID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;